export TERM="konsole-256color"
export TERM_PROGRAM="Konsole"
export PS1="\u\[\e[90m\] \h\[\e[m\] \[\e[92m\]\W\[\e[m\] \[\e[92m\]λ\[\e[m\] "
alias ta="tmux attach"
alias tn="tmux new"
alias vim="nvim"
alias ls="ls --color=auto"
alias dir="dir --color=auto"
alias vdir="vdir --color=auto"
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"
export PATH="/home/coder/.local/bin/:$PATH"
